# Generated by Django 4.0.3 on 2022-03-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuestionarioCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('fecha_asignacion', models.DateTimeField(verbose_name='Fecha de Solucion')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Apellido Paterno')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SolucionCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('fecha_solucion', models.DateTimeField(verbose_name='Fecha de Solucion')),
                ('fecha_revision', models.DateTimeField(verbose_name='Apellido Paterno')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('respuesta', models.CharField(max_length=250, verbose_name='Respuesta')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje Obtenido')),
                ('intentos', models.IntegerField(default=0, verbose_name='Intentos')),
                ('intentos_posibles', models.IntegerField(default=0, verbose_name='Cantidad de Intentos')),
                ('puntaje_pregunta', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Puntaje de la Pregunta')),
            ],
        ),
    ]
