# Generated by Django 4.0.3 on 2022-07-23 22:58

from django.db import migrations, models
import django.db.models.deletion
import educasec.utils.defs
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('fecha_asignacion', models.DateTimeField(verbose_name='Fecha de Asignacion')),
                ('fecha_expiracion', models.DateTimeField(verbose_name='Fecha de Expiracion')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=functools.partial(educasec.utils.defs.update_filename, *(), **{'model_name': 'cuestionario_banco', 'path_name': '2022/07/23'}), verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuestionarioPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('intentos_disponibles', models.IntegerField(default=1)),
                ('puntaje_asignado', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('texto', models.CharField(max_length=150, verbose_name='Texto')),
                ('tipo', models.CharField(choices=[('O', 'Domiciliado'), ('R', 'Respuesta Simple')], default='R', max_length=1, verbose_name='Tipo de Pregunta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=functools.partial(educasec.utils.defs.update_filename, *(), **{'model_name': 'pregunta_banco', 'path_name': '2022/07/23'}), verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntaOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('texto', models.CharField(max_length=250)),
                ('correcta', models.CharField(choices=[('C', 'Correcta'), ('I', 'Incorrecta')], default='I', max_length=1, verbose_name='¿Es correcta?')),
                ('pregunta_banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cuestionarios.preguntabanco')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('fecha_solucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solucion')),
                ('fecha_revision', models.DateTimeField(auto_now=True, verbose_name='Fecha Revision')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentario')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.alumno')),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to='cuestionarios.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='SolucionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.CharField(default='A', max_length=1)),
                ('respuesta', models.CharField(max_length=250, verbose_name='Respuesta')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje Obtenido')),
                ('intentos_tomados', models.IntegerField(default=0, verbose_name='Intentos')),
                ('comentario', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comentario')),
                ('situacion_respuesta', models.CharField(choices=[('B', 'Buena'), ('P', 'Pasable'), ('M', 'Mala')], default='P', max_length=1, verbose_name='Situacion de Respuesta')),
                ('cuestionario_pregunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionarios.cuestionariopregunta')),
                ('pregunta_opcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuestionarios.preguntaopcion')),
                ('solucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones_preguntas', to='cuestionarios.solucion')),
            ],
        ),
    ]
