# Generated by Django 4.0.3 on 2022-03-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucionpregunta',
            name='pregunta_opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.preguntaopcion'),
        ),
        migrations.AddField(
            model_name='solucionpregunta',
            name='solucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.solucioncuestionario'),
        ),
    ]
