# Generated by Django 4.0.3 on 2022-08-11 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('institucion', '0001_initial'),
        ('cuestionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.alumno'),
        ),
        migrations.AddField(
            model_name='solucion',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soluciones', to='cuestionarios.cuestionario'),
        ),
        migrations.AddField(
            model_name='preguntaopcion',
            name='pregunta_banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cuestionarios.preguntabanco'),
        ),
        migrations.AddField(
            model_name='preguntabanco',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.tipocurso'),
        ),
        migrations.AddField(
            model_name='cuestionariopregunta',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionario_preguntas', to='cuestionarios.cuestionario'),
        ),
        migrations.AddField(
            model_name='cuestionariopregunta',
            name='pregunta_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuestionario_preguntas', to='cuestionarios.preguntabanco'),
        ),
        migrations.AddField(
            model_name='cuestionariobanco',
            name='preguntas_banco',
            field=models.ManyToManyField(to='cuestionarios.preguntabanco'),
        ),
        migrations.AddField(
            model_name='cuestionariobanco',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.tipocurso'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='cuestionario_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuestionarios', to='cuestionarios.cuestionariobanco'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='solucionpregunta',
            unique_together={('solucion', 'cuestionario_pregunta')},
        ),
        migrations.AlterUniqueTogether(
            name='solucion',
            unique_together={('alumno', 'cuestionario')},
        ),
        migrations.AlterUniqueTogether(
            name='cuestionariopregunta',
            unique_together={('pregunta_banco', 'cuestionario')},
        ),
    ]
