# Generated by Django 4.0.3 on 2022-03-18 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
        ('cuestionarios', '0002_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucioncuestionario',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.alumno'),
        ),
        migrations.AddField(
            model_name='solucioncuestionario',
            name='cuestionario_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionariocurso'),
        ),
        migrations.AddField(
            model_name='cuestionariocurso',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cuestionario'),
        ),
        migrations.AddField(
            model_name='cuestionariocurso',
            name='curso_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursodocente'),
        ),
        migrations.AlterUniqueTogether(
            name='solucionpregunta',
            unique_together={('solucion', 'pregunta_opcion')},
        ),
        migrations.AlterUniqueTogether(
            name='solucioncuestionario',
            unique_together={('alumno', 'cuestionario_curso')},
        ),
    ]
