# Generated by Django 4.2 on 2023-04-24 00:21

from django.db import migrations, models
import educasm.utils.defs
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0004_alter_cuestionario_imagen_alter_pregunta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(educasm.utils.defs.update_filename, *(), **{'model_name': 'cuestionario_banco', 'path_name': '2023/04/23'}), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(educasm.utils.defs.update_filename, *(), **{'model_name': 'pregunta', 'path_name': '2023/04/23'}), verbose_name='Imagen'),
        ),
    ]
