# Generated by Django 4.1 on 2023-05-09 02:54

from django.db import migrations, models
import educasm.utils.defs
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionarios', '0005_alter_cuestionario_imagen_alter_pregunta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(educasm.utils.defs.update_filename, *(), **{'model_name': 'cuestionario_banco', 'path_name': '2023/05/08'}), verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(educasm.utils.defs.update_filename, *(), **{'model_name': 'pregunta', 'path_name': '2023/05/08'}), verbose_name='Imagen'),
        ),
    ]
