# Generated by Django 4.0.3 on 2022-03-14 14:02

from django.db import migrations, models
import educasec.utils.defs
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('estate', models.BooleanField(default=True)),
                ('titulo', models.CharField(default='', max_length=500, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('contenido', models.CharField(max_length=500, verbose_name='Contenido')),
                ('tipo', models.CharField(max_length=1, verbose_name='Tipo')),
                ('original_filename', models.FileField(upload_to=functools.partial(educasec.utils.defs.update_filename, *(), **{'model_name': 'recurso', 'path_name': '2022/03/14'}), verbose_name='Archivo Original')),
                ('miniatura', models.ImageField(blank=True, null=True, upload_to=functools.partial(educasec.utils.defs.update_filename, *(), **{'model_name': 'recurso', 'path_name': '2022/03/14'}), verbose_name='Miniatura')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
