# Generated by Django 4.0.3 on 2022-03-16 22:45

from django.db import migrations, models
import educasec.utils.defs
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='miniatura',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(educasec.utils.defs.update_filename, *(), **{'model_name': 'recurso', 'path_name': '2022/03/16'}), verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='original_filename',
            field=models.FileField(upload_to=functools.partial(educasec.utils.defs.update_filename, *(), **{'model_name': 'recurso', 'path_name': '2022/03/16'}), verbose_name='Archivo Original'),
        ),
    ]
