# Generated by Django 4.0.3 on 2022-03-12 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
        ('alumno', '0001_initial'),
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solucionpregunta',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solucionpregunta',
            name='opcion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.preguntaopcion'),
        ),
        migrations.AddField(
            model_name='solucionpregunta',
            name='pregunta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.pregunta'),
        ),
        migrations.AddField(
            model_name='solucionpregunta',
            name='solucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.solucioncuestionario'),
        ),
        migrations.AddField(
            model_name='solucionpregunta',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solucioncuestionario',
            name='alumno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
        ),
        migrations.AddField(
            model_name='solucioncuestionario',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solucioncuestionario',
            name='cuestionario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cuestionario'),
        ),
        migrations.AddField(
            model_name='solucioncuestionario',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='alumno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.alumno'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='docente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.docente'),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='creation_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='update_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_update', to=settings.AUTH_USER_MODEL),
        ),
    ]
