# Generated by Django 4.0.3 on 2022-03-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institucion', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docenteinstitucion',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.docente'),
        ),
        migrations.AddField(
            model_name='docenteinstitucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion'),
        ),
        migrations.AddField(
            model_name='cursodocente',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='cursodocente',
            name='docente_institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.docenteinstitucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.grado'),
        ),
        migrations.AddField(
            model_name='cuestionariopregunta',
            name='cuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cuestionario'),
        ),
        migrations.AddField(
            model_name='cuestionariopregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.pregunta'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='alumnoinscripcioncurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.alumno'),
        ),
        migrations.AddField(
            model_name='alumnoinscripcioncurso',
            name='curso_docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursodocente'),
        ),
        migrations.AlterUniqueTogether(
            name='docenteinstitucion',
            unique_together={('institucion', 'docente')},
        ),
        migrations.AlterUniqueTogether(
            name='cuestionariopregunta',
            unique_together={('pregunta', 'cuestionario')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnoinscripcioncurso',
            unique_together={('alumno', 'curso_docente')},
        ),
    ]
