# Generated by Django 4.0.3 on 2023-03-16 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('institucion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.tipocurso'),
        ),
        migrations.AddField(
            model_name='alumnoinscripcioncurso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucion.alumno'),
        ),
        migrations.AddField(
            model_name='alumnoinscripcioncurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso'),
        ),
        migrations.AlterUniqueTogether(
            name='alumnoinscripcioncurso',
            unique_together={('alumno', 'curso')},
        ),
    ]
