# Generated by Django 4.0.3 on 2022-03-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursodocente',
            old_name='año',
            new_name='year',
        ),
    ]
